name: ofertas
description: Ofertas ya.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  build_runner: ^2.1.10
  cloud_firestore: ^3.1.13
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.16
  firebase_storage: ^10.2.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.3.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  mockito: ^5.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
